### ISSUE TITLE
Adding support for multiple languages and internationalization

### ISSUE THREAD

**Issue by sudee404** [sudee404/Book-Review-Application#13]
### Description
Currently, our book review application only supports one language. In order to cater to a larger audience, we need to add support for multiple languages and internationalization. This will enable users from different regions to use the application in their preferred language.

### Proposed Solution
We will use Django's built-in internationalization framework to implement this feature. We will create language-specific message files and translate all the text strings in our application to different languages. We will also provide users with an option to choose their preferred language, and the application will display the content in the selected language.

### Tasks

- Research Django's internationalization framework
- Identify the languages to support
- Translate all text strings in the application
- Implement language selection feature
- Test the application in different languages

### Additional Considerations

- We need to consider the impact of language changes on the database schema and ensure that it is compatible with all supported languages.
- We should also ensure that the translations are accurate and culturally appropriate.

### Issue Checklist

- [ ]  Research Django's internationalization framework
- [ ]  Identify the languages to support
- [ ]  Translate all text strings in the application
- [ ]  Implement language selection feature
- [ ]  Test the application in different languages
- [ ]  Update the documentation with instructions on how to use the language selection feature.
